export const ar = {
	language: "العربيه",
	registration: {
		register: "تسجيل ",
		createAnAccount: "انشاء حساب جديد",
		firstName: "الاسم الاول",
		lastName: "الاسم الاخير",
		mobileNumber: "رقم الهاتف",
		role: "الدور",
		whatsAppNumber: "رقم الواتس اب",
		companyName: "اسم الشركة",
		password: "الرقم السرى",
		confirmPassword: "تاكيد الرقم السرى",
		work: " العمل / الحقل",
		field: "المجال",
		description: "الوصف",
		country: "البلد",
		governorate: "المحافظة",
		address: "العنوان",
		companyPhoneNumber: "رقم الشركة",
		commercialRecord: "سجل تجارى",
		commercialRecordOptional: " (اختياري)سجل تجارى",
		uploadCompanyLogo: "حمل لوجو الشركة (اختياري)",
		optional: "اختياري",
		acceptTermsOfServiceAndPrivacyPolicy: "قبول شروط الخدمة و الخصوصية",
		alreadyHaveAnAccount: "هل لديك حساب ؟",
		signIn: "تسجيل الدخول",
		email: "البريد الالكتروني",
		job: "الوظيفة",
		companyMail: "البريد الالكتروني للشركة (اختياري)",
		companyWebsite: "موقع  الالكتروني الشركة",
		companyWebsiteOptional: "موقع الالكتروني للشركة (اختياري)",
		company: "شركة",
		individual: "فرد",
		buyer: "مشترى",
		Contractor: "مقاول",
		admin: "المسؤل",
		employee: "موظف",
		Supplier: "مورد",
		userType: "نوع المستخدم",
		organisationLegalStructure: "نوع الشركة القنوني",
		pleaseChooseCountryFirst: "برجاء اختيار البلد اولا",
		pleaseFillAllRequiredFields: "برجاء املئ جميع الخانات *",
		pleaseFillFirstName: "* برجاء املئ الاسم الاخير",
		pleaseFillLastName: "* برجاء املئ الاسم الاخير",
		pleaseChooseCompanyName: "* برجاء اختار اسم الشركة",
		pleaseChooseWork: "* برجاء اختار مجالات العمل ",
		pleaseFillmobileNumber: "* برجاء املئ رقم الهاتف ",
		pleaseFillEmail: "* برجاء املئ  البريد الالكتروني ",
		pleaseFillPassword: "* برجاء املئ كلمة السر ",
		pleaseFillConfirmPassword: "* برجاء املئ تأكيد كلمة السر ",
		pleaseChooseCompanyType: "* برجاء اختار نوع  الشركة ",
		pleaseFillCompanyWebsite: "* برجاء املئ موقع  الالكتروني للشركة",
		pleaseChooseCountry: "* برجاء اختار البلد",
		pleaseChooseGovernorate: "* برجاء اختار المحافظه",
		pleaseFillAddress: "* برجاء املئ العنوان ",
		pleaseUploadCommercialRecord: "* برجاء رفع سجل الشركة ",
		pleaseChooseYourRole: "* برجاء اختار الوظيفة  ",
	},
	footer: {
		copyRights: "٢٠٢١ شيك , كل الحقوق محفوظه",
	},
	navbar: {
		login: "تسجيل الدخول",
		contactus: "اتصل بينا",
		pricing: "السعر",
		blog: " المقالات ",
		aboutus: "معلومات عنا",
		home: "الرئيسيه ",
	},
	contactus:{
		ourContactus:"اتصل بينا",
		home:"الرئيسيه",
		contactus:"اتصل بينا",
		pragraph:"يسعدنا مناقشة وضع مؤسستك. لذا يرجى الاتصال بنا عبر التفاصيل أدناه ، أو إدخال طلبك.",
		name:"الاسم",
		email:"البريد الالكتروني",
		phoneNumber:"رقم الهاتف",
		yourQuestion:"سؤالك",
		submit:"ارسال",
		alert:"برجاء ملئ جميع الحقول",
		touch:"تواصل معنا للحصول على أي نوع من المساعدة والمعلومات",
		addresstitle:"عنوان مكتبنا الرئيسي:",
		address:"3556 هارتفورد واي فيليدج ، ماونت بليزانت ، 29466 ، أستراليا.",
		callHelping:"اطلب المساعدة",
		mailInfotitle:" راسلنا للحصول على معلومات"


		
	},
	login: {
		signin: "تسجيل الدخول",
		mobileNumber: "رقم الهاتف",
		email: "البريد الالكتروني",
		password: "الرقم المرور",
		forgetPassword: "هل نسيت كلمة المرور ؟",
		didHaveAnAcount: "هل لديك حساب ؟",
		registerNow: "سجل الان !",
		signInWithMobileNumber: "هل تريد التسجيل برقم الهاتف ؟",
		signInWithMobileEmail: "هل تريد التسجيل بالبريد الالكتروني ؟",
		confirmPassword: "تاكيد الرقم السرى",
		save: "حفظ",
		forgetPasswordTitle: "نسيت كلمة المرور",
		RememberYourPassword: "هل تتذكر كلمة المرور ؟",
		send: "ارسال",
		emailIsRequired: "البريد الالكترونى مطلوب",
		passwordIsRequired: " كلمة السر مطلوب",
		confirmPasswordIsRequired: " تأكيد كلمة السر مطلوبه",
		ResetPassword: " اعادة تعيين كلمة المرور",
		passwordConfirmationDoesnotMatch: "كلمة المرور غير متطابقه",
		mobileNumberIsRequired: "رقم الهاتف مطلوب",
		verifyYourMailNow: " تحقق من البريد الالكترونى",
	},
};
