export const en = {
  language: "English",
  registration: {
    register: "Register ",
    createAnAccount: "Create An Account",
    firstName: "First Name",
    lastName: "Last Name",
    mobileNumber: "Mobile Number",
    role: "Role",
    whatsAppNumber: "WhatsApp Number",
    companyName: "Company Name",
    password: "Password",
    confirmPassword: "Confirm Password",
    work: "Work / Field",
    field: "Field",
    description: "Description",
    country: "Country",
    governorate: "Governorate",
    address: "Address",
    companyPhoneNumber: "Company Phone Number",
    commercialRecord: "Commercial Record ",
    uploadCompanyLogo: "Upload Company Logo( Optional )",
    optional: "Optional",
    acceptTermsOfServiceAndPrivacyPolicy:
      "Accept Terms of Service and Privacy Policy",
    alreadyHaveAnAccount: "Already Have An Account?",
    signIn: "Sign In",
    email: "Email",
    job: "Job",
    companyMail: "Company Mail ( Optional )",
    companyWebsite: "Company Website",
    companyWebsiteOptional: "Company Website (Optional)",
    company: "Company",
    individual: "Individual",
    buyer: "Buyer",
    Contractor: "Contractor",

    admin: "Admin",
    employee: "Employee",
    Supplier: "Supplier",
    userType: "User type",
    commercialRecordOptional: "commercialRecord (Optional)",
    organisationLegalStructure: "Organisation Legal Structure",
    pleaseChooseCountryFirst: "please Choose Country First",
    PleaseFillAllRequiredFields: "please Fill All Required Fields *",
    pleaseFillFirstName: "* Please fill firstName",
    pleaseFillLastName: "* Please fill lastName",
    pleaseChooseCompanyName: "* please Choose CompanyName",
    PleaseChooseWork: "* Please Choose Work",
    pleaseFillmobileNumber: "* please Fill mobileNumber",
    pleaseFillEmail: "* please Fill Email",
    pleaseFillPassword: "* please Fill Password",
    pleaseFillConfirmPassword: "* please Fill Confirm Password",
    pleaseChooseCompanyType: "* Please Choose Company Type",
    pleaseFillCompanyWebsite: "* please Fill CompanyWebsite",
    pleaseFillCountry: "* please Fill Country",
    pleaseChooseGovernorate: "* Please Choose Governorate",
    pleaseFillAddress: "* please Fill Address",
    pleaseUploadCommercialRecord: "* please Upload CommercialRecord",
    pleaseChooseYourRole: "* please Choose Your Role  ",
  },
  footer: {
    copyRights: "2021 Shayyek. All Rights Reserved",
  },

  navbar: {
    login: "Login",
    contactus: "Contactus",
    pricing: "Pricing",
    blog: " Blog ",
    aboutus: " Aboutus",
    home: "Home ",
  },
  contactus: {
    ourContactus: "Our Contact us",
    home: "Home",
    contactus: "contact us",
    pragraph:
      "We’re glad to discuss your organisation’s situation. So please contact us via the details below, or enter your request.",
    name: "Name",
    email: "E-mail",
    phoneNumber: "Phone Number",
    yourQuestion: "Your Question",
    submit: "Submit",
    alert: "Please fill your filed",
	touch:"Get in touch for any kind of help and information",
	addresstitle:" Our head office address:",
	address:"3556 Hartford Way Village, Mount Pleasant, SC, 29466, Australia.",
	callHelping:"Call For Help",
	mailInfotitle:" Mail us for information"
  },
  
  login: {
		signin: "Sign in",
		mobileNumber: "Mobile Number",
		email: "Email",
		password: "Password",
		forgetPassword: "Forget Password ?",
		didHaveAnAcount: "Didn’t Have an acount ?",
		registerNow: "Register Now !",
		signInWithMobileNumber: "Sign in With Mobile Number ?",
		signInWithMobileEmail: "Sign in With E-mail ?",
		confirmPassword: "Confirm Password",
		save: "Save",
		forgetPasswordTitle: "forget Password ",
		RememberYourPassword: "Remember Your Password?",
		send: "Send",
		emailIsRequired: "Email is required",
		passwordIsRequired: "password is required",
		confirmPasswordIsRequired: "confirm Password is required",
		ResetPassword: "Reset Password",
		passwordConfirmationDoesnotMatch: "password confirmation doesn't match",
		mobileNumberIsRequired: "mobileNumber is required",
		verifyYourMailNow: "Verify your mail Now",
	},
};
